os: linux
dist: xenial
language: python
sudo: true
python:
  - "3.6"
  - "3.7"

install:
  - sudo apt-get -qq update
  - sudo apt-get -y install tesseract-ocr tesseract-ocr-chi-sim libtesseract-dev libleptonica-dev pkg-config
  - pip install pytest
  - pip install findit-client
  - pip install Pillow
  - pip install findtext
  - pip install .

script:
  - cd sample
  - python demo.py
  - python short.py
  - cd ..
  - pytest tests/
